services:
  servicehost:
    image: servicehost:dev

    container_name: servicehost
    
    ports:
      - "8084:8080"
    
    depends_on:
      mysql:
        condition: service_healthy

    environment:
      ASPNETCORE_ENVIRONMENT: Docker

    networks:
      - lampshade_network
  mysql:
    image: mysql:8.4
    
    container_name: mysql
    restart: unless-stopped
    
    environment:
      MYSQL_ROOT_PASSWORD: "1384"
      MYSQL_DATABASE: LampshadeTest
    
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-init-scripts:/docker-entrypoint-initdb.d/
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    networks:
      - lampshade_network
networks:
  lampshade_network:
    driver: bridge

volumes:
  mysql-data: