services:
  servicehost:
    image: servicehost:dev
    container_name: servicehost
    expose:
      - "8080"
    ports:
      - "8080:8080"
    
    depends_on:
      mysql:
        condition: service_healthy

    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__LampshadeDB=Server=mysql;Port=3306;Database=LampshadeTets;User=root;Password=1384;AllowPublicKeyRetrieval=True;SslMode=None;Connect Timeout=120;Default Command Timeout=120;Keepalive=60;Connection Idle Timeout=300;Pooling=True;Min Pool Size=1;Max Pool Size=20;
    networks:
      - lampshade_network
  mysql:
    image: mysql:8.4
    
    container_name: mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "1384"
      MYSQL_DATABASE: LampshadeTest
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    networks:
      - lampshade_network
networks:
  lampshade_network:
    driver: bridge

volumes:
  mysql-data: