<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\AccountManagement.Application.Contract\AccountManagement.Application.Contract.csproj"/>
        <ProjectReference Include="..\ShopManagementDomain\ShopManagementDomain.csproj"/>
    </ItemGroup>

</Project>
