<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.24">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AccountManagement.Infrastructure.Configuration\AccountManagement.Infrastructure.Configuration.csproj" />
    <ProjectReference Include="..\BlogManagemenet.Infrastructure.Configuration\BlogManagement.Infrastructure.Configuration.csproj" />
    <ProjectReference Include="..\CommentManagement.Infrastructure.Configuration\CommentManagement.Infrastructure.Configuration.csproj" />
    <ProjectReference Include="..\DiscountManagmenet.Infrastructure.Configuration\DiscountManagement.Infrastructure.Configuration.csproj" />
    <ProjectReference Include="..\InventoryManagement.Infrastructure.Configuration\InventoryManagement.Infrastructure.Configuration.csproj" />
    <ProjectReference Include="..\ShopManagment.Infrastructure.Configuration\ShopManagement.Infrastructure.Configuration.csproj" />
    <ProjectReference Include="..\_01_LampshadeQuery\_01_LampshadeQuery.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Pages\Shared\Components\ProductCategoryWithProduct\" />
    <Folder Include="wwwroot\ProductPictures\" />
    <Folder Include="wwwroot\ProductPictures\ProfilePhoto\" />
  </ItemGroup>

  <ItemGroup>
    <_ContentIncludedByDefault Remove="wwwroot\ProductPictures\ProfilePhoto\Admin\2026-03-12-16-15-03-profile.jpg" />
  </ItemGroup>

</Project>
