<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.24">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.2" />
        <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="8.0.3" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\BlogManagement,Application.Contract\BlogManagement.Application.Contract.csproj" />
        <ProjectReference Include="..\BlogManagement.Application\BlogManagement.Application.csproj" />
        <ProjectReference Include="..\BlogManagement.Infrastructure\BlogManagement.Infrastructure.EFCore.csproj" />
        <ProjectReference Include="..\BlogManagmenet.Domain\BlogManagement.Domain.csproj" />
        <ProjectReference Include="..\_01_LampshadeQuery\_01_LampshadeQuery.csproj" />
    </ItemGroup>

</Project>
